# you need to edit this section
# NOTE: I am not committing real values here, obviously.
# BUT, when i shift to running the display, the default will be useable.
# if you want more than one system, change this!

# for a standalone display.
wifi_ssid = "fencing1"
wifi_password = "count 2 say blue"

display_ip = "192.168.4.1"
display_port = 5000

fencer = "right"  # or left, but nothing else - and we'll complain!

# items below this line shouldn't be edited in general.
# NOTE: you can't use floats directly due to the subset of toml implemented by circuitpython.
sampling_rate_Hz = 100000
sampling_time_sec = "0.014"  # probably should be the same as the minimal valid touch time.
# i'm ok with these being integers,
left_Hz = 7000
right_Hz = 8000
min_valid_power = "5e10"
lockout_time_sec = "0.3"  # this shouldn't really be here? it's the responsibility of the display / server / arbitrator.
dormant_after_hit_sec = "3.0"
message_repeat_min_sec = "0.01"
message_repeat_max_sec = "0.05"