# if you want more than one system, change wireless ssid at least.

# for a standalone display.
wifi_ssid = "fencing1"
wifi_password = "count 2 say blue"

display_ip = "192.168.4.1"
display_port = 5000

# for wired setups:
# if positive, we'll disable the internal pullups (which are 45kOhm, too weak really),
# and rely on external ones. Zero might make sense for non esp32-s3 hardware.
# no effect for wireless setups.
HAVE_EXTERNAL_PULLUPS = 1

# for (wireless) fencer boxes (the display will ignore this.)
fencer = "right"  # or left, but nothing else - and we'll complain!

# items below this line shouldn't be edited in general.
# NOTE: you can't use floats directly due to the subset of toml implemented by circuitpython.
# so float values are given as strings and converted in code, and i've tried to avoid it mostly.
sampling_rate_Hz = 50000

buzzer_time_msec = 1000
# amount of time display remains lit
delay_before_display_reset_msec = 2000

# reference :
# FIE material rules : https://static.fie.org/uploads/34/172612-book%20m%20ang.pdf
lockout_msec = 300
send_touch_for_msec = 125
# techincally 14+-1 msec.
# Allowing for sampling_time_msec != min_touch_msec
# used by the fencer box to handle processing time; the idea is that we sample with enough
# timing margin to allow processing to finish before min time, then busy wait and check
# at the end of the min_touch window.
# since we detect touch - sample - process - check if we're still touching.
sampling_time_msec = 10
min_touch_msec = 14

# i'm ok with these being integers,
# the left and right frequencies are those emitted (put on lame) by that side
# i.e. they are the ones the other side is checking for.
left_Hz = 7000
right_Hz = 8000
min_valid_power = "1e10"
dormant_after_hit_msec = 50  # had it long initially, in practice setting to near zero.
message_repeat_min_msec = 10
message_repeat_max_msec = 50